# docker-compose.yaml
services:
  nm-vllm:
    image: ghcr.io/neuralmagic/nm-vllm-openai:v0.2.0
    command: --model neuralmagic/TinyLlama-1.1B-Chat-v1.0-marlin --disable-log-request
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  prometheus:
    image: prom/prometheus:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
