name: Nightly
run-name: ${{ github.actor }} triggered nightly on ${{ github.ref }}
on:
    schedule:
      # * is a special character in YAML so you have to quote this string
      - cron: '0 1 * * *'

    workflow_dispatch:
      inputs:
        push_benchmark_results_to_gh_pages:
          description: "When set to true, the workflow pushes all benchmarking results to gh-pages UI "
          type: choice
          options:
              - 'true'
              - 'false'
          default: 'false'

jobs:

    BUILD:
        uses: ./.github/workflows/build.yml
        with:
            build_label: gcp-build-static
            timeout: 60
            gitref: ${{ github.ref }}
            Gi_per_thread: 1
            nvcc_threads: 4
            python: 3.10.12
        secrets: inherit

    TEST-SOLO:
        needs: [BUILD]
        if: success()
        uses: ./.github/workflows/test.yml
        with:
            test_label: aws-avx2-32G-a10g-24G
            timeout: 480
            gitref: ${{ github.ref }}
            python: 3.10.12
            whl: ${{ needs.BUILD.outputs.whl }}
            test_skip_list: neuralmagic/tests/skip-almost-all.txt
        secrets: inherit

    TEST-MULTI:
        needs: [BUILD]
        if: success()
        uses: ./.github/workflows/test.yml
        with:
            test_label: aws-avx2-192G-4-a10g-96G
            timeout: 480
            gitref: ${{ github.ref }}
            python: 3.10.12
            whl: ${{ needs.BUILD.outputs.whl }}
            test_skip_list: neuralmagic/tests/skip-almost-all.txt
        secrets: inherit

    BENCHMARK:
        needs: [BUILD]
        if: success()
        uses: ./.github/workflows/nm-benchmark.yml
        with:
            label: aws-avx2-32G-a10g-24G
            benchmark_config_list_file:  ./.github/data/nm_benchmark_nightly_configs_list.txt
            timeout: 720
            gitref: '${{ github.ref }}'
            python: 3.10.12
            # Always push if it is a scheduled job
            push_benchmark_results_to_gh_pages: "${{ github.event_name == 'schedule' || inputs.push_benchmark_results_to_gh_pages }}"
        secrets: inherit

    # TODO: decide if this should build or use the whl
    # single gpu
    Accuracy-Smoke-AWS-AVX2-32G-A10G-24G:
        uses: ./.github/workflows/nm-lm-eval-smoke.yml
        with:
            label: aws-avx2-32G-a10g-24G
            timeout: 240
            gitref: '${{ github.ref }}'
            Gi_per_thread: 12
            nvcc_threads: 1
            python: "3.10.12"
        secrets: inherit
