name: remote push
run-name: ${{ github.actor }} verifying branch '${{ github.ref }}'
on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

    BUILD:
        uses: ./.github/workflows/build.yml
        with:
            build_label: gcp-build-static
            timeout: 60
            gitref: ${{ github.ref }}
            Gi_per_thread: 1
            nvcc_threads: 4
            python: 3.10.12
        secrets: inherit

    TEST-SOLO:
        needs: [BUILD]
        if: success()
        uses: ./.github/workflows/test.yml
        with:
            test_label: aws-avx2-32G-a10g-24G
            timeout: 480
            gitref: ${{ github.ref }}
            python: 3.10.12
            whl: ${{ needs.BUILD.outputs.whl }}
            test_skip_list: neuralmagic/tests/skip-almost-all.txt
        secrets: inherit

    BENCHMARK:
        needs: [BUILD]
        if: success()
        uses: ./.github/workflows/nm-benchmark.yml
        with:
            label: aws-avx2-32G-a10g-24G
            benchmark_config_list_file:  ./.github/data/nm_benchmark_remote_push_configs_list.txt
            timeout: 180
            gitref: '${{ github.ref }}'
            python: 3.10.12
            push_benchmark_results_to_gh_pages: "false"
        secrets: inherit
